version: "2"

services:
  restapi:
    build: ./restapi
    container_name: restapi
    ports:
      - "4444:4000"
    links:
      - influxdb
    depends_on:
      - influxdb

  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "8080:80"
    depends_on:
      - influxdb
      - restapi
    links:
      - influxdb
      - restapi

  influxdb:
    container_name: influxdb
    image: influxdb:alpine
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
  load_data:
    container_name: load_data
    build: ./influxdb/load_data
    depends_on:
      - influxdb